save_dir: ./saved_models
save_name: uda_cifar100_2000_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
log_every_epoch: 5
save_every_epoch: 5
num_train_sample: 15000
num_train_iter: 102401
num_eval_iter: 5000
num_labels: 2000
batch_size: 64
eval_batch_size: 1024
TSA_schedule: none
T: 0.4
p_cutoff: 0.8
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
net: WideResNet
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
dropout: 0.0
data_dir: ./data
dataset: cifar100
train_sampler: RandomSampler
num_classes: 100
num_workers: 5
alg: uda
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10032
dist_backend: nccl
gpu: 0
